/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThemeImport } from './routes/theme'
import { Route as LikesImport } from './routes/likes'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ThemeRoute = ThemeImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRoute,
} as any)

const LikesRoute = LikesImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesImport
      parentRoute: typeof rootRoute
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/likes': typeof LikesRoute
  '/theme': typeof ThemeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/likes': typeof LikesRoute
  '/theme': typeof ThemeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/likes': typeof LikesRoute
  '/theme': typeof ThemeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/likes' | '/theme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/likes' | '/theme'
  id: '__root__' | '/' | '/likes' | '/theme'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LikesRoute: typeof LikesRoute
  ThemeRoute: typeof ThemeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LikesRoute: LikesRoute,
  ThemeRoute: ThemeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/likes",
        "/theme"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/likes": {
      "filePath": "likes.tsx"
    },
    "/theme": {
      "filePath": "theme.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
