/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TDSTailwind } from "./components/typography/index";
export { TDSTailwind } from "./components/typography/index";
export namespace Components {
    interface HeroSection {
    }
    interface MainApp {
    }
    interface TdsTypography {
        "align": TDSTailwind['textAlign'];
        "classCustom": string;
        "color": TDSTailwind['color'];
        "content": HTMLElement | string | undefined;
        "uppercase": boolean;
        "variant": TDSTailwind['fontSize'];
        "weight": TDSTailwind['fontWeight'];
    }
    interface TopNavBar {
    }
}
declare global {
    interface HTMLHeroSectionElement extends Components.HeroSection, HTMLStencilElement {
    }
    var HTMLHeroSectionElement: {
        prototype: HTMLHeroSectionElement;
        new (): HTMLHeroSectionElement;
    };
    interface HTMLMainAppElement extends Components.MainApp, HTMLStencilElement {
    }
    var HTMLMainAppElement: {
        prototype: HTMLMainAppElement;
        new (): HTMLMainAppElement;
    };
    interface HTMLTdsTypographyElement extends Components.TdsTypography, HTMLStencilElement {
    }
    var HTMLTdsTypographyElement: {
        prototype: HTMLTdsTypographyElement;
        new (): HTMLTdsTypographyElement;
    };
    interface HTMLTopNavBarElement extends Components.TopNavBar, HTMLStencilElement {
    }
    var HTMLTopNavBarElement: {
        prototype: HTMLTopNavBarElement;
        new (): HTMLTopNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "hero-section": HTMLHeroSectionElement;
        "main-app": HTMLMainAppElement;
        "tds-typography": HTMLTdsTypographyElement;
        "top-nav-bar": HTMLTopNavBarElement;
    }
}
declare namespace LocalJSX {
    interface HeroSection {
    }
    interface MainApp {
    }
    interface TdsTypography {
        "align"?: TDSTailwind['textAlign'];
        "classCustom"?: string;
        "color"?: TDSTailwind['color'];
        "content"?: HTMLElement | string | undefined;
        "uppercase"?: boolean;
        "variant"?: TDSTailwind['fontSize'];
        "weight"?: TDSTailwind['fontWeight'];
    }
    interface TopNavBar {
    }
    interface IntrinsicElements {
        "hero-section": HeroSection;
        "main-app": MainApp;
        "tds-typography": TdsTypography;
        "top-nav-bar": TopNavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hero-section": LocalJSX.HeroSection & JSXBase.HTMLAttributes<HTMLHeroSectionElement>;
            "main-app": LocalJSX.MainApp & JSXBase.HTMLAttributes<HTMLMainAppElement>;
            "tds-typography": LocalJSX.TdsTypography & JSXBase.HTMLAttributes<HTMLTdsTypographyElement>;
            "top-nav-bar": LocalJSX.TopNavBar & JSXBase.HTMLAttributes<HTMLTopNavBarElement>;
        }
    }
}
