/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ThemeLazyImport = createFileRoute('/theme')()
const BenchmarkLikesLazyImport = createFileRoute('/benchmark/likes')()

// Create/Update Routes

const ThemeLazyRoute = ThemeLazyImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/theme.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BenchmarkLikesLazyRoute = BenchmarkLikesLazyImport.update({
  id: '/benchmark/likes',
  path: '/benchmark/likes',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/benchmark/likes.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeLazyImport
      parentRoute: typeof rootRoute
    }
    '/benchmark/likes': {
      id: '/benchmark/likes'
      path: '/benchmark/likes'
      fullPath: '/benchmark/likes'
      preLoaderRoute: typeof BenchmarkLikesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme': typeof ThemeLazyRoute
  '/benchmark/likes': typeof BenchmarkLikesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme': typeof ThemeLazyRoute
  '/benchmark/likes': typeof BenchmarkLikesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/theme': typeof ThemeLazyRoute
  '/benchmark/likes': typeof BenchmarkLikesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/theme' | '/benchmark/likes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theme' | '/benchmark/likes'
  id: '__root__' | '/' | '/theme' | '/benchmark/likes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemeLazyRoute: typeof ThemeLazyRoute
  BenchmarkLikesLazyRoute: typeof BenchmarkLikesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemeLazyRoute: ThemeLazyRoute,
  BenchmarkLikesLazyRoute: BenchmarkLikesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/theme",
        "/benchmark/likes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/theme": {
      "filePath": "theme.lazy.tsx"
    },
    "/benchmark/likes": {
      "filePath": "benchmark/likes.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
