/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ThemeLazyImport = createFileRoute('/theme')()
const LottiestonpackLazyImport = createFileRoute('/lotties_tonpack')()
const LottiesLazyImport = createFileRoute('/lotties')()

// Create/Update Routes

const ThemeLazyRoute = ThemeLazyImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/theme.lazy').then((d) => d.Route))

const LottiestonpackLazyRoute = LottiestonpackLazyImport.update({
  id: '/lotties_tonpack',
  path: '/lotties_tonpack',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/lotties_tonpack.lazy').then((d) => d.Route),
)

const LottiesLazyRoute = LottiesLazyImport.update({
  id: '/lotties',
  path: '/lotties',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/lotties.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lotties': {
      id: '/lotties'
      path: '/lotties'
      fullPath: '/lotties'
      preLoaderRoute: typeof LottiesLazyImport
      parentRoute: typeof rootRoute
    }
    '/lotties_tonpack': {
      id: '/lotties_tonpack'
      path: '/lotties_tonpack'
      fullPath: '/lotties_tonpack'
      preLoaderRoute: typeof LottiestonpackLazyImport
      parentRoute: typeof rootRoute
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lotties': typeof LottiesLazyRoute
  '/lotties_tonpack': typeof LottiestonpackLazyRoute
  '/theme': typeof ThemeLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lotties': typeof LottiesLazyRoute
  '/lotties_tonpack': typeof LottiestonpackLazyRoute
  '/theme': typeof ThemeLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lotties': typeof LottiesLazyRoute
  '/lotties_tonpack': typeof LottiestonpackLazyRoute
  '/theme': typeof ThemeLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lotties' | '/lotties_tonpack' | '/theme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lotties' | '/lotties_tonpack' | '/theme'
  id: '__root__' | '/' | '/lotties' | '/lotties_tonpack' | '/theme'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LottiesLazyRoute: typeof LottiesLazyRoute
  LottiestonpackLazyRoute: typeof LottiestonpackLazyRoute
  ThemeLazyRoute: typeof ThemeLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LottiesLazyRoute: LottiesLazyRoute,
  LottiestonpackLazyRoute: LottiestonpackLazyRoute,
  ThemeLazyRoute: ThemeLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lotties",
        "/lotties_tonpack",
        "/theme"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lotties": {
      "filePath": "lotties.lazy.tsx"
    },
    "/lotties_tonpack": {
      "filePath": "lotties_tonpack.lazy.tsx"
    },
    "/theme": {
      "filePath": "theme.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
